[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "uni-proxy"
version = "0.1.0"
description = ""
readme = "README.md"
license = { text = "GPLv3" }
authors = [{ name = "Lanqing Huang", email = "lqhuang@outlook.com" }]
requires-python = ">=3.8"
dependencies = ["attrs", "tomlkit", "strictyaml", "httpx[socks]"]

[project.optional-dependencies]
dev = ["mypy", "black", "isort", "ruff", "typing_extensions"]
test = ["pytest"]
